### ISSUE TITLE
Something wrong with logs encoding

### ISSUE THREAD

**Issue by glmn** [glmn/PUBGDiscoBot#23]
```
2019-09-01 00:37:23.454 | MSG      | __main__:on_message:153 - [VÈŃØM||491114283711594506] #general||491114283711594508 @babaimonda
--- Logging error in Loguru Handler #3 ---
Record was: {'elapsed': datetime.timedelta(seconds=47462, microseconds=377604), 'exception': None, 'extra': {}, 'file': 'main.py', 91114283711594508 @babaimondal||617433258526900264 > !pdb-track', 'module': 'main', 'name': '__main__', 'process': '6676', 'thread'nds=10800), 'RTZ 2 (ceia)'))}
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\loguru\_handler.py", line 144, in emit
    self._writer(str_record)
  File "C:\Python37\lib\site-packages\loguru\_file_sink.py", line 71, in write
    self._file.write(message)
  File "C:\Python37\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 24-26: character maps to <undefined>
--- End of logging error ---
```

**Comment by glmn** [comment]
Fixed with passing `encoding="utf8"` to logger.add()
Thanks to https://github.com/Delgan/loguru/issues/124#issuecomment-526870880

**Comment by glmn** [comment]
rfx
