### ISSUE TITLE
RateLimit exception

### ISSUE THREAD

**Issue by glmn** [glmn/PUBGDiscoBot#26]
```
Task exception was never retrieved
future: <Task finished coro=<main_loop() done, defined at .\main.py:52> exception=RateLimitError('Too many requests. Limit: 10 Reset: 2019-09-08 00:50:27')>
Traceback (most recent call last):
  File ".\main.py", line 72, in main_loop
    players_wo_matches = [player for player in players_data
  File "C:\Python37\lib\site-packages\pubg_python\decorators.py", line 23, in wrapper
    self.fetch()
  File "C:\Python37\lib\site-packages\pubg_python\querysets.py", line 45, in fetch
    self._data = self.client.request(self.endpoint)
  File "C:\Python37\lib\site-packages\pubg_python\clients.py", line 32, in request
    raise exception(response_headers=response.headers)
pubg_python.exceptions.RateLimitError: Too many requests. Limit: 10 Reset: 2019-09-08 00:50:27
```

**Comment by glmn** [comment]
Fixed in https://github.com/glmn/PUBGDiscoBot/commit/b02be320129a60815cf14289c15e585b87655338
